"""Tests for engine/image_io.py against the synthetic-photo proxies in
synthetic_photos/ (generated by generate_synthetic_photos.py from real,
already-validated Kaggle CSV patterns -- see that module's docstring for
why synthetic photos, not real ones, are used for ground-truth testing).

These tests are skipped if the synthetic photo set hasn't been generated
(keeps the main suite runnable without the image_io dependencies/fixtures
present), rather than failing.
"""

from __future__ import annotations

import json
import os

import cv2
import numpy as np
import pytest
from scipy.spatial import cKDTree

from engine import image_io

SYNTHETIC_DIR = os.path.join(os.path.dirname(__file__), "..", "synthetic_photos")
MATCH_TOLERANCE_PX = 6.0

pytestmark = pytest.mark.skipif(
    not os.path.isdir(SYNTHETIC_DIR) or not os.listdir(SYNTHETIC_DIR),
    reason="synthetic_photos/ not generated -- run generate_synthetic_photos.py first",
)


def _load_ground_truth(stem: str) -> dict:
    with open(os.path.join(SYNTHETIC_DIR, f"{stem}.json")) as f:
        return json.load(f)


def _image_path(stem: str) -> str:
    return os.path.join(SYNTHETIC_DIR, f"{stem}.jpg")


def _deskewed_gt_pixels(stem: str, preprocessed: image_io.Preprocessed) -> np.ndarray:
    """Ground-truth dot pixel positions, rotated into the SAME deskewed
    frame preprocess() produced (see validate_image_io.py for why this
    is necessary: comparing raw pixel positions across the pre- and
    post-deskew frames is an apples-to-oranges coordinate mismatch)."""
    gt = _load_ground_truth(stem)
    gt_px = np.array(list(gt["dot_pixel_positions"].values()), dtype=np.float32)
    img = cv2.imread(_image_path(stem))
    h, w = img.shape[:2]
    M = cv2.getRotationMatrix2D((w / 2, h / 2), preprocessed.rotation_deg, 1.0)
    return cv2.transform(gt_px.reshape(-1, 1, 2), M).reshape(-1, 2)


@pytest.mark.parametrize("stem", ["kolam19_k1", "kolam19_k2"])
def test_detect_lattice_dot_count_matches_ground_truth(stem):
    gt = _load_ground_truth(stem)
    preprocessed = image_io.preprocess(_image_path(stem))
    lattice = image_io.detect_lattice(preprocessed)

    # allow a small tolerance for spurious/missed detections rather than
    # demanding an exact count match
    assert abs(len(lattice.lattice_coords) - gt["n_nodes"]) <= max(2, round(0.03 * gt["n_nodes"]))


@pytest.mark.parametrize("stem", ["kolam19_k1", "kolam19_k2"])
def test_detect_lattice_positions_match_ground_truth_within_tolerance(stem):
    preprocessed = image_io.preprocess(_image_path(stem))
    lattice = image_io.detect_lattice(preprocessed)
    gt_px = _deskewed_gt_pixels(stem, preprocessed)
    det_px = np.array(lattice.pixel_positions)

    tree = cKDTree(det_px)
    d, _ = tree.query(gt_px)
    matched_fraction = (d < MATCH_TOLERANCE_PX).mean()
    assert matched_fraction > 0.95


@pytest.mark.parametrize("stem", ["kolam19_k1", "kolam19_k2"])
def test_trace_path_edge_set_matches_ground_truth_within_tolerance(stem):
    """Edges are compared as DISTINCT connectivity (not exact strand
    multiplicity -- see engine.motifs.compression_ratio's docstring for
    why that's the primary currency used elsewhere in this project too),
    after remapping recovered lattice coordinates onto ground-truth node
    labels via nearest detected-dot-to-ground-truth-dot pixel matching."""
    gt = _load_ground_truth(stem)
    preprocessed = image_io.preprocess(_image_path(stem))
    lattice = image_io.detect_lattice(preprocessed)
    recovered_edges = image_io.trace_path(preprocessed, lattice)

    gt_px = _deskewed_gt_pixels(stem, preprocessed)
    gt_labels = list(gt["dot_pixel_positions"].keys())
    det_px = np.array(lattice.pixel_positions)

    tree_gt = cKDTree(gt_px)
    d, idx = tree_gt.query(det_px)
    recovered_to_gt = {}
    for i, (dist, j) in enumerate(zip(d, idx)):
        if dist < MATCH_TOLERANCE_PX:
            node = tuple(int(v) for v in gt_labels[j].split(","))
            recovered_to_gt[lattice.lattice_coords[i]] = node

    recovered_distinct = {
        frozenset({recovered_to_gt[a], recovered_to_gt[b]})
        for a, b in recovered_edges
        if a in recovered_to_gt and b in recovered_to_gt
    }
    gt_distinct = {frozenset({tuple(a), tuple(b)}) for a, b in gt["edges"]}

    recall = len(recovered_distinct & gt_distinct) / len(gt_distinct)
    precision = len(recovered_distinct & gt_distinct) / len(recovered_distinct)
    assert recall > 0.95
    assert precision > 0.95


def _blob_binary(centers, size=400, radius=8):
    """A minimal synthetic binary ink mask with round dot-like blobs at
    `centers` -- for testing detect_lattice's degenerate-input handling
    without depending on an external real photo file."""
    binary = np.zeros((size, size), dtype=np.uint8)
    yy, xx = np.mgrid[0:size, 0:size]
    for cx, cy in centers:
        mask = (xx - cx) ** 2 + (yy - cy) ** 2 <= radius**2
        binary[mask] = 255
    return binary


def test_detect_lattice_handles_zero_candidate_dots_without_crashing():
    preprocessed = image_io.Preprocessed(binary=np.zeros((400, 400), dtype=np.uint8), rotation_deg=0.0)
    lattice = image_io.detect_lattice(preprocessed)
    assert lattice.lattice_coords == []
    assert lattice.pixel_positions == []


def test_detect_lattice_handles_one_candidate_dot_without_crashing():
    # Regression test: found on a real (non-synthetic) low-light Wikimedia
    # Commons photo, session 10 -- Otsu's global threshold misclassified
    # most of the dark, low-contrast image as "ink," producing a single
    # spurious dot-like blob. _fit_lattice_coords' affine fit needs >=3
    # points and previously raised numpy.linalg.LinAlgError: Singular
    # matrix on exactly this input. Must now return a clean degenerate
    # result instead of crashing.
    binary = _blob_binary([(200, 200)])
    preprocessed = image_io.Preprocessed(binary=binary, rotation_deg=0.0)
    lattice = image_io.detect_lattice(preprocessed)  # must not raise
    assert lattice.lattice_coords == []
    assert len(lattice.pixel_positions) == 1


def test_detect_lattice_handles_two_candidate_dots_without_crashing():
    # Same underlying degeneracy as the one-dot case (still < 3 points,
    # an affine fit is still underdetermined) -- must not crash either.
    binary = _blob_binary([(100, 100), (300, 300)])
    preprocessed = image_io.Preprocessed(binary=binary, rotation_deg=0.0)
    lattice = image_io.detect_lattice(preprocessed)  # must not raise
    assert lattice.lattice_coords == []
    assert len(lattice.pixel_positions) == 2


def test_detect_lattice_still_fits_a_real_lattice_with_enough_dots():
    # Guard rail: the >=3-point degenerate-input fix must not accidentally
    # break the normal case. 5 dots on a clean grid -> a real lattice fit.
    centers = [(100, 100), (150, 100), (200, 100), (100, 150), (100, 200)]
    binary = _blob_binary(centers, size=400, radius=8)
    preprocessed = image_io.Preprocessed(binary=binary, rotation_deg=0.0)
    lattice = image_io.detect_lattice(preprocessed)
    assert len(lattice.lattice_coords) == 5
    assert len(set(lattice.lattice_coords)) == 5  # every dot gets a distinct coordinate


def test_build_graph_produces_engine_compatible_multigraph():
    """The single public entry point should hand back exactly the format
    engine/graph_io.py produces: an nx.MultiGraph with (int, int) nodes,
    consumable by motifs/symmetry/generation/validity with zero changes."""
    import networkx as nx

    from engine import motifs, validity

    G = image_io.build_graph(_image_path("kolam19_k1"))
    assert isinstance(G, nx.MultiGraph)
    assert G.number_of_nodes() > 0
    assert all(
        isinstance(n, tuple) and len(n) == 2 and all(isinstance(v, int) for v in n) for n in G.nodes()
    )

    # zero-change downstream compatibility: these calls must not raise
    result = validity.check_validity(G)
    assert "is_eulerian_circuit" in result

    dots = set(G.nodes())
    interior = motifs.interior_points(dots, radius=1)
    placements, residual, _fully_covered = motifs.induce_motif_set_adaptive(
        G, interior, dots, max_radius=2, max_motifs_per_radius=50
    )
    assert isinstance(placements, list)


HELDOUT_DIR = os.path.join(os.path.dirname(__file__), "..", "synthetic_photos_heldout")


@pytest.mark.skipif(
    not os.path.isdir(HELDOUT_DIR) or not os.listdir(HELDOUT_DIR),
    reason="synthetic_photos_heldout/ not generated -- run generate_synthetic_photos_heldout.py first",
)
def test_dense_pattern_dot_recall_regression_kolam29_k50():
    """Regression test for the Task B threshold fix (session 10): before
    the fix, detect_lattice's threshold_abs was anchored to the GLOBAL
    max distance-transform value (effectively the single largest/least-
    degraded dot's size), which was systematically too strict for dense
    (kolam29-scale) patterns -- verified root cause: 0 spurious
    detections, but 120/484 real dots missed, 99.2% of those with their
    OWN distance-transform value below the old threshold (not suppressed
    by min_distance -- a genuine intensity-gate rejection). kolam29_k50
    is the documented worst held-out case: dot recall was 0.752 before
    the fix, must now be >0.99."""
    img_path = os.path.join(HELDOUT_DIR, "kolam29_k50.jpg")
    with open(os.path.join(HELDOUT_DIR, "kolam29_k50.json")) as f:
        gt = json.load(f)

    preprocessed = image_io.preprocess(img_path)
    lattice = image_io.detect_lattice(preprocessed)

    img = cv2.imread(img_path)
    h, w = img.shape[:2]
    M = cv2.getRotationMatrix2D((w / 2, h / 2), preprocessed.rotation_deg, 1.0)
    gt_px = np.array(list(gt["dot_pixel_positions"].values()), dtype=np.float32)
    gt_px = cv2.transform(gt_px.reshape(-1, 1, 2), M).reshape(-1, 2)

    det_px = np.array(lattice.pixel_positions)
    tree = cKDTree(det_px)
    d, _ = tree.query(gt_px)
    recall = (d < MATCH_TOLERANCE_PX).mean()
    assert recall > 0.99  # was 0.752 before the fix


def test_dense_pattern_threshold_fix_does_not_regress_sparse_patterns():
    """Guard rail: THRESHOLD_ABS_FRAC's reduction must not cost sparse
    (kolam19) patterns anything -- verified empirically to be a genuine
    no-op there (the old threshold was never their binding constraint)."""
    lattice = image_io.detect_lattice(image_io.preprocess(_image_path("kolam19_k1")))
    gt = _load_ground_truth("kolam19_k1")
    assert len(lattice.lattice_coords) == gt["n_nodes"]


def test_analyze_kolam_type_sikku_and_kambi():
    """Verify analyze_kolam_type correctly distinguishes Sikku loop patterns (with half-integer nodes) from Kambi direct-line patterns (integer nodes only)."""
    import networkx as nx

    # Sikku Graph: contains half-integer node offsets like (0.5, 0.5)
    G_sikku = nx.MultiGraph()
    G_sikku.add_edge((0, 0), (0.5, 0.5))
    G_sikku.add_edge((0.5, 0.5), (1, 1))
    assert image_io.analyze_kolam_type(G_sikku) == "SIKKU_LOOP"

    # Kambi Graph: integer lattice nodes only
    G_kambi = nx.MultiGraph()
    G_kambi.add_edge((0, 0), (1, 0))
    G_kambi.add_edge((1, 0), (1, 1))
    assert image_io.analyze_kolam_type(G_kambi) == "KAMBI_DIRECT_LINE"


def test_analyze_kolam_type_multi_loop_sikku():
    """Verify analyze_kolam_type correctly identifies multi-loop Sikku graphs with >1 connected components."""
    import networkx as nx

    # Disjoint sub-loops with half-integer nodes
    G_multi = nx.MultiGraph()
    # Loop 1
    G_multi.add_edge((0, 0), (0.5, 0.5))
    G_multi.add_edge((0.5, 0.5), (1, 1))
    # Loop 2 (disjoint)
    G_multi.add_edge((5, 5), (5.5, 5.5))
    G_multi.add_edge((5.5, 5.5), (6, 6))

    assert image_io.analyze_kolam_type(G_multi) == "MULTI_LOOP_SIKKU"


def test_decompose_multi_loop_graph():
    """Verify decompose_multi_loop_graph splits a multi-loop graph into distinct sub-graphs for each closed loop/component."""
    import networkx as nx

    G_multi = nx.MultiGraph()
    # Loop 1
    G_multi.add_edge((0, 0), (0.5, 0.5))
    G_multi.add_edge((0.5, 0.5), (1, 1))
    # Loop 2
    G_multi.add_edge((5, 5), (5.5, 5.5))
    G_multi.add_edge((5.5, 5.5), (6, 6))

    subgraphs = image_io.decompose_multi_loop_graph(G_multi)
    assert len(subgraphs) == 2
    assert set(subgraphs[0].nodes).isdisjoint(set(subgraphs[1].nodes))


