"""add user_id to generation_requests

Revision ID: 65648c1f34c0
Revises: fa68873a45be
Create Date: 2026-08-15 18:18:31.061613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65648c1f34c0'
down_revision: Union[str, None] = 'fa68873a45be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_requests', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_generation_requests_user_id'), 'generation_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_requests_user_id'), table_name='generation_requests')
    op.drop_column('generation_requests', 'user_id')
    # ### end Alembic commands ###
