"""initial schema

Revision ID: 70f7d9edcb46
Revises: 
Create Date: 2026-08-14 14:38:47.960549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f7d9edcb46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('checkpoint_path', sa.String(length=512), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pattern_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pattern_id', sa.String(length=36), nullable=False),
    sa.Column('representation_json', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.Text(), nullable=True),
    sa.Column('n_dots', sa.Integer(), nullable=False),
    sa.Column('n_distinct_edges', sa.Integer(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_versions_fingerprint'), 'pattern_versions', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_pattern_versions_pattern_id'), 'pattern_versions', ['pattern_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pattern_version_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_type', sa.String(length=16), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pattern_version_id'], ['pattern_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('model_version_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('total_latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['generation_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_runs_created_at'), 'generation_runs', ['created_at'], unique=False)
    op.create_table('pattern_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pattern_version_id', sa.String(length=36), nullable=False),
    sa.Column('vertices', sa.Integer(), nullable=False),
    sa.Column('edges', sa.Integer(), nullable=False),
    sa.Column('distinct_edges', sa.Integer(), nullable=False),
    sa.Column('connected_components', sa.Integer(), nullable=False),
    sa.Column('graph_density', sa.Float(), nullable=True),
    sa.Column('odd_degree_vertex_count', sa.Integer(), nullable=False),
    sa.Column('largest_component_covers_all_nodes', sa.Boolean(), nullable=False),
    sa.Column('is_eulerian_circuit', sa.Boolean(), nullable=False),
    sa.Column('has_eulerian_path', sa.Boolean(), nullable=False),
    sa.Column('max_multiplicity', sa.Integer(), nullable=False),
    sa.Column('multiplicity_distribution', sa.JSON(), nullable=False),
    sa.Column('multiplicity_violations', sa.Integer(), nullable=False),
    sa.Column('symmetry_coverage', sa.Float(), nullable=True),
    sa.Column('symmetry_transform', sa.String(length=32), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('density_score', sa.Float(), nullable=True),
    sa.Column('novelty_score', sa.Float(), nullable=True),
    sa.Column('nearest_source_id', sa.String(length=64), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pattern_version_id'], ['pattern_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern_version_id')
    )
    op.create_table('verification_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pattern_version_id', sa.String(length=36), nullable=False),
    sa.Column('model_version_id', sa.String(length=36), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('n_expected', sa.Integer(), nullable=True),
    sa.Column('n_detected', sa.Integer(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['pattern_version_id'], ['pattern_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_results_pattern_version_id'), 'verification_results', ['pattern_version_id'], unique=False)
    op.create_table('generation_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('pattern_version_id', sa.String(length=36), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pattern_version_id'], ['pattern_versions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['generation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_results_run_id'), 'generation_results', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_results_run_id'), table_name='generation_results')
    op.drop_table('generation_results')
    op.drop_index(op.f('ix_verification_results_pattern_version_id'), table_name='verification_results')
    op.drop_table('verification_results')
    op.drop_table('pattern_analysis')
    op.drop_index(op.f('ix_generation_runs_created_at'), table_name='generation_runs')
    op.drop_table('generation_runs')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_pattern_versions_pattern_id'), table_name='pattern_versions')
    op.drop_index(op.f('ix_pattern_versions_fingerprint'), table_name='pattern_versions')
    op.drop_table('pattern_versions')
    op.drop_table('model_versions')
    op.drop_table('patterns')
    op.drop_table('models')
    op.drop_table('generation_requests')
    # ### end Alembic commands ###
